### ISSUE TITLE
Display notifications in it's own menu item

### ISSUE THREAD

**Issue by orlando** [debtcollective/header#6]
Discourse displays all notifications inside the user profile menu. This menu has also links related to users that are handled as icons, and these can't be descriptive enough for all users.

![image](https://user-images.githubusercontent.com/849872/53656762-e37d4f00-3c19-11e9-857d-d2e3b9646858.png)

By moving notifications to its own container, we can change from icons to text links to make it more understandable to users.

A good example we can use for desktop the following one

![image](https://user-images.githubusercontent.com/849872/53656907-4c64c700-3c1a-11e9-96a2-8ef77b736135.png)

For mobile, we will display notifications as a full-screen view.

Once we implement this in the header, we will port it to the Community in another ticket.

## Acceptance criteria

- Notifications should be rendered in its own container
- Notifications should follow design recommendations described above.

**Comment by duranmla** [comment]
This ticket seems to be very related to #4 and for the implementation of this notification panel we will change the big avatar by the icons shown by discourse and keep them up-to two lines. In that way, we will have a more closer look/approach than the Discourse has

**Comment by duranmla** [comment]
Making a minor update here, I am having issues seems I realize that the dropdown from MU is very tight to its built-in implementation and it is difficult to customize, thus, I needed to create a new component **NotificationsPanel** in order to achieve what we need.

At this point, I have created a basic **NotificationPanel** that I will try to put in context and make sure it will behave similar to the dropdown, once get there I can add the final styles. I have also mapped the icons we are going to use for each notification.

**Comment by duranmla** [comment]
The current state of this issue is this:
![http://recordit.co/ahHNV13Uox](http://recordit.co/ahHNV13Uox.gif)

I still need to:
- [ ] Fix some flow type issues
- [ ] Make sure notifications items are clickable

After those, I can make a PR and wait for feedback.
